function covid19sorted = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COVID19SORTED = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  COVID19SORTED = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  covid19sorted = importfile("C:\Users\warned\OneDrive - Queensland University of Technology\Documents\Postdoc_ACEMS_AIMS\COVID19\Data\COVID19data\data-raw\covid19_sorted.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Mar-2020 15:56:25

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["CountryRegion", "ProvinceState", "date", "confirmed", "recovered", "deaths", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "active"];
opts.SelectedVariableNames = ["CountryRegion", "ProvinceState", "date", "confirmed", "recovered", "deaths", "active"];
opts.VariableTypes = ["categorical", "categorical", "datetime", "double", "double", "double", "string", "string", "string", "string", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var7", "Var8", "Var9", "Var10", "Var11", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["CountryRegion", "ProvinceState", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "date", "InputFormat", "yyyy-MM-dd");

% Import the data
covid19sorted = readtable(filename, opts);

end