function fulllist = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FULLLIST = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  FULLLIST = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  fulllist = importfile("C:\Users\warned\OneDrive - Queensland University of Technology\Documents\Postdoc_ACEMS_AIMS\COVID19\Data\COVID-19_ISO-3166\full_list.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Mar-2020 12:31:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["CountryRegion", "alpha3", "long", "lat", "population"];
opts.VariableTypes = ["categorical", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["CountryRegion", "alpha3"], "EmptyFieldRule", "auto");

% Import the data
fulllist = readtable(filename, opts);

end