function JohnsHopkinstoA3 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  JOHNSHOPKINSTOA3 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  JOHNSHOPKINSTOA3 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  JohnsHopkinstoA3 = importfile("C:\Users\warned\OneDrive - Queensland University of Technology\Documents\Postdoc_ACEMS_AIMS\COVID19\Data\COVID-19_ISO-3166\JohnsHopkins-to-A3.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Mar-2020 12:30:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["CountryRegion", "alpha3"];
opts.VariableTypes = ["categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["CountryRegion", "alpha3"], "EmptyFieldRule", "auto");

% Import the data
JohnsHopkinstoA3 = readtable(filename, opts);

end